# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a78473c9fb388bc7835fd35633d526926f3543cb8dfa6924b3f92ac159e283138e7effb33693e3895dd9b286db2ca704849df0450d5361bd56e46a5e8b5bde7

test:
  secret_key_base: a18c7957ac7e873a14d57bc57453815017861869ffa5f6921d86c09a317b4f7c3023e809d0b83f877830a257e186fc2931bbf67801e25f77efa17e5e98c311b6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
